### ISSUE TITLE
AttributeError: 'VmDebootstrap' object has no attribute 'logging

### ISSUE THREAD

**Issue by florath** [florath/vmdebootstrap#2]
The latest codehelp/modules branch version stops with:

Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/cliapp/app.py", line 189, in _run
self.process_args(args)
File "/root/vmdebootstrap/bin/vmdebootstrap", line 218, in process_args
self.start_ops()
File "/root/vmdebootstrap/bin/vmdebootstrap", line 294, in start_ops
self.debootstrap(rootdir)
File "/root/vmdebootstrap/bin/vmdebootstrap", line 466, in debootstrap
self.logging.debug("debootstrap arguments: %s", args)
AttributeError: 'VmDebootstrap' object has no attribute 'logging'

**Comment by florath** [comment]
Commit 0a08716df25349907a1c7043c4753ab190851d4f fixed this.
